steps:
- name: 'us-central1-docker.pkg.dev/wiz-environment-692908/wiz-demo/wizcli:latest'
  entrypoint: 'bash'
  script: |
    #!/usr/bin/env bash
    terraform init 
    terraform validate
    terraform show -json tfplan.binary > tfplan.json
    wizcli auth --id=$$ID --secret=$$SECRET
    wizcli iac scan --path tfplan.json --policy "test-iac-demo-policy"
  secretEnv: ['ID', 'SECRET']
  dir: Storage
  
availableSecrets:
  secretManager:
  - versionName: projects/578507508040/secrets/WIZSECRET/versions/1
    env: 'SECRET'
  - versionName: projects/578507508040/secrets/WIZID/versions/1
    env: 'ID'